[meta]
name = "Height Tracker"
author = "socramdavid"
category = "Utilities"
version = "1.1.2"
siteid = 530

[script]
imports = [ "Formatting.as", "Time.as" ]
dependencies = ["MLHook", "MLFeedRaceData", "PlayerState", "VehicleState"] # need both

